# Generated by Django 4.0.4 on 2022-08-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(default='', max_length=5)),
                ('priority', models.CharField(default='', max_length=6)),
                ('assignedTo', models.TextField()),
                ('createdAt', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('role', models.CharField(default='', max_length=8)),
                ('auth_key', models.TextField()),
            ],
        ),
    ]
